### ISSUE TITLE
TensorFlow 1.1 Windows GPU Optimized For i7-4510U

### ISSUE THREAD

**Issue by Carmezim** [yaroslavvb/tensorflow-community-wheels#12]
TensorFlow: 1.1
Computing Capability: 5.0
XLA: No (not supported on Windows)
CUDA: 8.0
cuDNN: 5.1

After weeks dealing with (experimental) Bazel to properly build TF on Windows it is alive [Wheel](https://drive.google.com/drive/folders/0BwSPPvGo-S_IQmNVeGJRSllCNm8?usp=sharing)

**Comment by yaroslavvb** [comment]
Why closed, doesn't work?

**Comment by Carmezim** [comment]
No, I realized it was compiled with MSVC which only supports AVX and AVX2 on x64 so I will do it with CMake instead of Bazel and add the available SIMD instructions for MSVC and update the wheel.

**Comment by spk921** [comment]
@Carmezim  Where can I find updated your whl? Is it possible to download?

**Comment by Carmezim** [comment]
@spk921 Unfortunately as I stated above it wasn't properly optimized. If you want to build with CMake enabling AVX/AVX2 (the two arch supported on 64-bit by MSVC) following [TensorFlow's guide](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake#tensorflow-cmake-build) let me know if you have any doubts I'd be glad to help as possible.
