### ISSUE TITLE
tensorflow-directml 1.15 cp3.7 windows amd64 NO AVX for old CPUS

### ISSUE THREAD

**Issue by BenjaminWegener** [yaroslavvb/tensorflow-community-wheels#203]
tensorflow-directml 1.15 cp3.7 windows amd64 NO AVX for old CPUS
[https://github.com/BenjaminWegener/tensorflow-community-wheels/archive/refs/heads/master.zip](https://github.com/BenjaminWegener/tensorflow-community-wheels/archive/refs/heads/master.zip)

**Comment by mirh** [comment]
Just for the records, that `_noAVX` in front of the architecture name makes pip unhappy.
