### ISSUE TITLE
Request - Tensorflow 2.3.x, No GPU, No AVX, Python 3.8, Ubuntu 18.04, Silvermont

### ISSUE THREAD

**Issue by youngsooroh** [yaroslavvb/tensorflow-community-wheels#213]
I am not successful in building TensorFlow myself yet and couldn't find any wheels for Silvermont with python 3.8 in Ubuntu 18.04 either. 

I was trying to build with the following option but didn't work.
(e.g,) -march=silvermont -mcx16 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mno-avx

Can anyone provide me with a wheel for any 2.x version if 2.3.x is not available? for silvermont in Ubuntu 18.04? 

Cheers,

**Comment by Novaal** [comment]
Hi @youngsooroh 

You could try a wheel for `westmere` from https://github.com/yaroslavvb/tensorflow-community-wheels/issues/202. This should work, as `silvermont` seams to support everything `westmere` is capable of (as of https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html).

For building the wheel i would do the following:

```bash
cd /tensorflow_src
```

Create the `.tf_configure.bazelrc` with the builtin `configure` script.
```bash
PYTHON_VERSION=python3.8
PYTHON_BIN_PATH=$(which $PYTHON_VERSION) \
PYTHON_LIB_PATH=$($PYTHON_VERSION -c "import pip; print(pip.__path__[0].rstrip('/pip'))") \
TF_NEED_CUDA=0 \
TF_NEED_ROCM=0 \
TF_DOWNLOAD_CLANG=0 \
CC_OPT_FLAGS="-march=silvermont -Wno-sign-compare" \
TF_SET_ANDROID_WORKSPACE=0 \
TF_ENABLE_XLA=1 \
TF_NEED_OPENCL_SYCL=0 \
TF_NEED_MPI=0 \
./configure
```

This produces in my case the following `.tf_configure.bazelrc` for Python 3.8.
```
build --action_env PYTHON_BIN_PATH="/usr/bin/python3.8"
build --action_env PYTHON_LIB_PATH="/usr/local/lib/python3.8/dist-packages"
build --python_path="/usr/bin/python3.8"
build:xla --define with_xla_support=true
build --config=xla
build:opt --copt=-march=silvermont
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu
test --build_tag_filters=-gpu
build --action_env TF_CONFIGURE_IOS="0"
```

Afterwards its possible to just compile:
```
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```

And to build the wheel to `/mnt`:
```bash
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /mnt
```

**Comment by youngsooroh** [comment]
@Novaal The Westmere wheel worked well! Thank you so much!
