### ISSUE TITLE
[Request] Tensorflow 1.2.1 with AVX, SSE4.1 and SSE4.2 -O3

### ISSUE THREAD

**Issue by oxydron** [yaroslavvb/tensorflow-community-wheels#30]
Could anyone compile this one with only those 3 flags? Linux and Python 3.5.x

**Comment by DzamoNorton** [comment]
I just uploaded a _fairly_ similar build but tensorflow 1.3 and no `-O` specified (not sure what it would have defaulted to).

**Comment by lakshayg** [comment]
I have one available with this exact configuration. See #19

**Comment by oxydron** [comment]
@DzamoNorton 1.3 even better and with the exactly flags I need. Thank you very much sir!

**Comment by DzamoNorton** [comment]
Sure.  Weirdly I found no noticeable improvement in RNN training over the stock build in pypi.  But I looked and there are AVX instructions in the object code so the compiler options were applied:

```
   67abd:	c5 fa 58 04 82       	vaddss (%rdx,%rax,4),%xmm0,%xmm0
   55632:	c5 bc 59 d2          	vmulps %ymm2,%ymm8,%ymm2
   69fb9:	c5 cb 58 d2          	vaddsd %xmm2,%xmm6,%xmm2
   66968:	c5 fc 59 a5 10 fe ff 	vmulps -0x1f0(%rbp),%ymm0,%ymm4
   71a9a:	c5 f4 59 ca          	vmulps %ymm2,%ymm1,%ymm1
   69985:	c5 ec 59 d4          	vmulps %ymm4,%ymm2,%ymm2
```

**Comment by oxydron** [comment]
Tested here with the lastest commit of Keras and got some errors(tested with the numpy downloaded by your wheel and conda installed version, both get errors).

Still looking for a wheel that works...
