### ISSUE TITLE
 Tensorflow 1.3.0 RC0 Ubuntu 16.04 CPU AVX, SSE4.1, SSE4.2, Python 3.5.2 

### ISSUE THREAD

**Issue by DzamoNorton** [yaroslavvb/tensorflow-community-wheels#32]
http://somecomputer.xyz/files/tensorflow-1.3.0rc0-cp35-cp35m-linux_x86_64.whl

Compiled with `-O3 -march=native` on an Intel(R) Core(TM) i5-3317U CPU

**Comment by mamrehn** [comment]
Thanks! Would be perfect with Python 3.6.2 though :)
