### ISSUE TITLE
Tensorflow (multiple versions w CPU/GPU) for Mac (rMBP m2012)

### ISSUE THREAD

**Issue by bodak** [yaroslavvb/tensorflow-community-wheels#33]
[https://github.com/bodak/tensorflow-wheels/releases](https://github.com/bodak/tensorflow-wheels/releases)

All releases built to support mid 2012 15" Macbook Pro Retina's specs as best as possible.

I will keep adding new versions to the repository as they come.

**Comment by diwu1989** [comment]
thx, and the latest 1.3 Mac CPU whl is
https://github.com/bodak/tensorflow-wheels/releases/download/1.3.0/tensorflow-1.3.0-cp27-cp27m-macosx_10_7_x86_64.whl

**Comment by cipri-tom** [comment]
I tried installing this in a python 2.7 environment (anaconda) but it fails as it tries to uninstall the global `six` dependency.
Any ideas as to why ?

**Comment by bodak** [comment]
Added 1.4.0-rc0 versions
