### ISSUE TITLE
Wheels at TinyMind

### ISSUE THREAD

**Issue by cipri-tom** [yaroslavvb/tensorflow-community-wheels#45]
Hey,

Just wanted to share with everyone that the guys at TinyMind also provide a nice set of wheels to TF. They are here: https://github.com/mind/wheels

Cheers!

**Comment by eggie5** [comment]
@cipri-tom these are not for mac right? looks like ubuntu?

**Comment by cipri-tom** [comment]
Yeap, it seems they are for ubuntu. I thought this repo is for all kinds of wheels?

**Comment by eggie5** [comment]
Yes, I was just confirming. Thanks for the great work you are doing especially getting CUDA 9 builds out there

**Comment by cipri-tom** [comment]
Hehe, I have no connection with the builds at TinyMind ^^. But I'm glad to spread the word 😃

**Comment by cipri-tom** [comment]
Closing, since it was already mentioned by them https://github.com/yaroslavvb/tensorflow-community-wheels/issues/34
