### ISSUE TITLE
Request for TF 1.12 for python 3.5 no AVX

### ISSUE THREAD

**Issue by qwertpi** [yaroslavvb/tensorflow-community-wheels#98]
I require CPU only Tensorflow verison 1.12 with no AVX for use on ubtunu xenial with python 3.5. Idealy with SSE4.1 and SSE4.2 support but this is not compulsory. My CPU is a x86_64 Intel Celeron 3215U
Thank you in advance, let me know if you need more information

**Comment by bzamecnik** [comment]
Yeah, I also need to compile something similar for my Pentium G4400 (TF 1.12, Python 3.5 no AVX). I'll try to make a build.

**Comment by qwertpi** [comment]
Thanks @bzamecnik

**Comment by bzamecnik** [comment]
I managed to install compatible version of Bazel (0.19.1) and configure TF (NCCL 1.3, compute capabilities 5.2,6.1). Now tests are running and then I'll start the build.

**Comment by bzamecnik** [comment]
Trying to compile Tensorflow is even more horrible experience than installing NVIDIA drivers. Error besides error, incompatible tools. I don't understand how they can their official builds done. 😠

**Comment by bzamecnik** [comment]
Finally I managed to build it. It's published in #99.

**Comment by qwertpi** [comment]
Thanks but your build seems to require CUDA and I did specify I wanted CPU tensorflow

**Comment by bzamecnik** [comment]
Aha, yeah I needed GPU version. I can try to build also the CPU variant.

**Comment by qwertpi** [comment]
Thanks, I really appreciate all the work you are putting into this

**Comment by bzamecnik** [comment]
OK, I started another build for CPU-only with SSE4.1, SSE4.2. I realized that in the previous build SSE4 was not enabled.

```
time bazel build -c opt \
            --copt=-mno-avx \
            --copt=-mno-avx2 \
            --copt=-mno-fma \
            --copt=-msse4.1 \
            --copt=-msse4.2 \
            --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
            //tensorflow/tools/pip_package:build_pip_package
```

GPU build took 4 and half hours. CPU one may be possibly a bit shorter.

**Comment by bzamecnik** [comment]
I'm afraid it got build with CUDA, even tough it was disabled. :/

You can try: http://data.neural.cz/tensorflow-wheels/tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl

**Comment by qwertpi** [comment]
Yeah, it still wants CUDA, thanks for trying though. I'll leave this issue open in case you or anyone else figures out how to make it work

**Comment by bzamecnik** [comment]
I'll run it again with clean and configure...

**Comment by bzamecnik** [comment]
The new CPU-only (hopefully) build is running. I'm afraid the last build turned out to be with CUDA since I forgot `TF_NEED_CUDA=1` exported. This time I removed it, ran `bazel clean`, `./configure`. Let's see. Anyway the second GPU build is better, so I updated the links.

**Comment by bzamecnik** [comment]
Here's the build wheel for CPU:
http://data.neural.cz/tensorflow-wheels/cpu-no-avx-sse4/tensorflow-1.12.0-cp35-cp35m-linux_x86_64.whl. Check the MD5 on the issue #99 page. Tested to work with `keras/examples/mnist_cnn.py`.

**Comment by qwertpi** [comment]
It works! I had to do a `sudo rm -r /usr/local/lib/python3.5/dist-packages/tensorflow/` to remove leftovers from old tensorflow to get it to work but now it does. Thanks a lot
